fail_fast: false
default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args: [--fix]

  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
